### ISSUE TITLE
It does not create the role on each member accounts

### ISSUE THREAD

**Issue by gugaiz** [aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#10]
On steps 2 it says 
"_Note: You only need to complete this step once from the management account (payer account)._" 
and it also says 
"_After CloudFormation creates the stack set, each member account in your organization has BillingConsolePolicyMigratorRole IAM role_" 
but after the stack is complete on the payer account, I checked the other member accounts and I didn't see any `BillingConsolePolicyMigratorRole` created there and I am getting the error below when running `python identify_affected_policies.py --all`

```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::<payer id account>:assumed-role/AWSReservedSSO_AWSAdministratorAccess_c2e87a8fc4e314e2/gugaiz is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<member account id>:role/BillingConsolePolicyMigratorRole
```

Should I manually run this stack on each member account?

**Comment by Lansoweb** [comment]
Same issue here.

For now, I've created the stack on each account. You can manually create the Role on each account too by copying from the main one.

**Comment by azzimuth** [comment]
I have the same issue even after creating the role in each AWS account... Any solution?

**Comment by Gagan-Nagaraju** [comment]
Can you share some details on what is seen on cloudformation console when stackset is deployed?
* Do you see any errors on `Stack Instances` tab? Does the status for reach stack instance say **Succeeded**?
* Can you go to cloudformation console of a member account, under stacks search for `BillingConsolePolicyMigratorRoleStackset` , go to this stack, check the status and if in case of failures, can you share what is seen on `Events` tab of this stack?

I'm trying to get as much information as possible to help me debug the issue and reproduce the error on my end.

**Comment by dlefebvre68** [comment]
@Lansoweb this should be run as a stack set, not a stack. I made the same mistake and had the same problem as you.

**Comment by dlefebvre68** [comment]
@gugaiz Please see my previous comment. May be too late, but you need to create a stack set, not a stack.

**Comment by gugaiz** [comment]
Thanks! I will close this ticket. Sorry for the misreading
