### ISSUE TITLE
There is not the action: "invoicing:UpdatePurchaseOrderStatus"

### ISSUE THREAD

**Issue by sudakos** [aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#11]
I don't think the following actions exist.” while “purchase-orders: updatepurchaseOrderStatus” exists.

file: policy_migration_scripts/config/action_mapping_config.json
line: 131
action: "invoicing:UpdatePurchaseOrderStatus"

**Comment by coverprice** [comment]
I concur, this line needs to be updated to `"purchase-orders:UpdatePurchaseOrderStatus",`.

**Comment by Gagan-Nagaraju** [comment]
Thanks for catching the issue and bringing it to our notice. I've updated the config.
