### ISSUE TITLE
Cannot Perform STS AssumeRole

### ISSUE THREAD

**Issue by Sriharsha-Uppala** [aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#15]
Creating the Stack in the payer account/Root Account does not create the Role in the member accounts. And it throws the error

An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam:::user/developers-virginia-access is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam:::role/BillingConsolePolicyMigratorRole

**Comment by Gagan-Nagaraju** [comment]
You need to create a **StackSet** in the management account, but looks like you are creating only a **Stack**
This issue looks a lot like this one: https://github.com/aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles/issues/10

Please have a look and let me know if this worked.
Additional reference on creating stackset can be found here: https://github.com/aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#step-2-create-the-cloudformation-stack-set

**Comment by Gagan-Nagaraju** [comment]
@Sriharsha-Uppala - Is this still an issue or can this be closed?

**Comment by Sriharsha-Uppala** [comment]
Thank you @Gagan-Nagaraju . The issue is Resolved now
