### ISSUE TITLE
Cannot perform the operation on the protected role

### ISSUE THREAD

**Issue by jrguayaws** [aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#9]
When running the scripts, roles and policies managed by AWS are showing. If they are left to be updated they throw an error. Example:

```
"GroupName": "Group1", 
"Account": "############", 
"PolicyType": "RoleInlinePolicy", 
"PolicyName": "AwsSSOInlinePolicy", 
"UserOrGroupOrRoleName": "AWSReservedSSO_RestrictedAdmin_01b9b74ca528d470", 
"Status": "FAILURE", 
"ErrorMessage": "UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSReservedSSO_RestrictedAdmin_01b9b74ca528d470' - this role is only modifiable by AWS"
```

These roles and policies should be either ignored (not shown) or fixed accordingly.

**Comment by Sriharsha-Uppala** [comment]
Creating the Stack in the payer account/Root Account does not create the Role in the member accounts. And it throws the error

 An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::************:user/developers-virginia-access is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::************:role/BillingConsolePolicyMigratorRole

**Comment by Gagan-Nagaraju** [comment]
The fix has been merged. Please re-run the scripts (Step 3 to Step 5 on README). This should update any impacted permission sets.
**NOTE:** You need few additional permissions when running the scripts to work specifically for permission sets. `These additional permissions are only needed to run the script`. **No changes needed for the cloudformation stack set**
Additional permissions:
```
"sso:ListInstances",
"sso:ListPermissionSets",
"sso:GetInlinePolicyForPermissionSet",
"sso:DescribePermissionSet",
"sso:PutInlinePolicyToPermissionSet",
"sso:ProvisionPermissionSet",
"sso:DescribePermissionSetProvisioningStatus",
"iam:GetRole",
"iam:ListAttachedRolePolicies"
```

Full list of permissions are mentioned here: https://github.com/aws-samples/bulk-policy-migrator-scripts-for-account-cost-billing-consoles#prerequisites
